Courses/urls.py
from django.contrib import admin
from django.urls import path, include
from Courses import views
urlpatterns = [
    path('all/', views.All_courses.as_view(), name='my_courses'),
]

Mentors/Mentors/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^Accounts/', include('Accounts.urls', namespace='Accounts')),
    url(r'^Accounts/', include('django.contrib.auth.urls')),
    #url(r'MentorsAccount/', include('MentorsAccount.urls', namespace='Account2')),
    #url(r'MentorsAccount/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^test2/$', views.TestPage2.as_view(), name='test2'),
    url(r'^thanks2/$', views.ThanksPage2.as_view(), name='thanks2'),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r"^groups/", include("groups.urls", namespace="groups"))
]

Mentors/sems/urls.py
from django.urls import include, path, re_path
from . import views

urlpatterns = [
    path('students/', views.students_view, name='students'),
    path('profile/<int:pk>', views.student_detail, name='student_detail'),
    path('user/delete/<int:pk>', views.user_delete, name='user_delete'),
    path('programs/', views.programs_view, name='programs'),
    path('programs/add/', views.program_add, name='program_add'),
    path('programs/edit/<int:pk>', views.program_edit, name='program_edit'),
    path('programs/delete/<int:pk>', views.program_delete, name='program_delete'),
    path('programs/<int:pk>/course/add/', views.course_add, name='course_add'),
    path('programs/<int:p_pk>/course/delete/<int:pk>', views.course_delete, name='course_delete'),
    path('programs/course/<int:pk>/edit/', views.course_edit, name='course_edit'),
    # path('programs/<int:pk>', views.program_detail, name='programs_detail'),
    path('programs/course/<int:pk>', views.course_detail, name='course_detail'),
    path('program/<int:pk>', views.program_detail, name='program_single'),
    path('program/course/<int:course_id>/upload/', views.handle_file_upload, name='upload_file_view'),
    path('program/course/<int:course_id>/edit/<int:file_id>', views.handle_file_edit, name='upload_file_edit'),
    path('program/course/<int:course_id>/delete/<int:file_id>', views.handle_file_delete, name='upload_file_delete'),
    path('students/add/', views.user_add, name='user_add'),
    path('profile/edit/<int:pk>', views.user_edit, name='user_edit'),
    path('course/<int:course_id>/teacher/edit/', views.select_teacher, name='add_teacher'),
    path('course/<int:course_id>/teacher/confirm/<int:student_id>', views.confirm_select_teacher, name='confirm_teacher'),
    path('course/<int:course_id>/teacher/delete/<int:student_id>', views.confirm_delete_teacher, name='delete_teacher'),
    path('ajax/filter_course/', views.filter_courses_view, name='filter_views'),
    path('post/<int:pk>', views.post_single, name='post_single'),
    path('post/add/', views.post_add, name='post_add'),
    path('post/edit/<int:pk>', views.post_edit, name='post_edit'),
    path('post/delete/<int:pk>', views.post_delete, name='post_delete'),
    path('course/<int:course_id>/grades/', views.grade_students, name='grade_students'),
    path('posts/', views.post_list, name='post_list'),
    re_path(r'^$', views.home_view, name='home'),
    path('settings/year/add/', views.year_add, name='year_add'),
    path('settings/year/edit/<int:pk>', views.year_edit, name='year_edit'),
    # path('settings/year/view/', views.current_years, name='current_years'),
    path('courses/register/', views.register_courses, name='register_courses'),
    path('register/course/<int:pk>/max/<int:max_reached>', views.register_course, name='reg_course'),
    # path('register/course/remove/<int:pk>', views.unregister_course, name='unreg_course'),
    path('provimet/paraqit/<int:c_pk>/<int:a_pk>', views.paraqit_provimin, name='paraqit_provimin'),
    path('provimet/paraqit/', views.paraqit_provimet, name='provimet'),
    path('provimet/paraqitura/', views.provimet_paraqitura, name='provimet_paraqitura'),
    path('administrator/<int:afat_extra>', views.admin_view, name='administrator'),
    path('afati/delete/<int:pk>', views.delete_afat, name='delete_afat'),

    # path('ajax/update/teacher/', views.update_teacher, name='update_teacher'),
]

Mentors/sems/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from datetime import datetime
from django import forms
from django.db.models.signals import post_save


STATUS = (
    (0, 'Ne progres'),
    (1, 'Aprovuar'),
    (2, 'Refuzuar'),
)

DAYS = (
    [(i, i) for i in range(1, 31)]
)

MONTHS = (
    (1, 'Janar'),
    (2, 'Shkurt'),
    (3, 'Mars'),
    (4, 'Prill'),
    (5, 'Maj'),
    (6, 'Qershor'),
    (7, 'Korrik'),
    (8, 'Gusht'),
    (9, 'Shtator'),
    (10, 'Tetor'),
    (11, 'Nentor'),
    (12, 'Dhjetor'),
)


YEARS = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
    )

SEMESTER = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
)

LEVELS = (
    ('Bachelor', 'Bachelor'),
    ('Master', 'Master'),
)

TYPES = (
    ('o', 'Obligative'),
    ('z', 'Zgjedhore'),
)


class Program(models.Model):
    name = models.CharField(max_length=150)
    summary = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=200)
    summary = models.TextField(max_length=600, null=True, blank=True)
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    credits = models.IntegerField(null=True, default=0)
    obligative = models.BooleanField(default=True)
    year = models.IntegerField(choices=YEARS, default=1)
    semester = models.IntegerField(choices=SEMESTER, default=1)
    level = models.CharField(max_length=100, choices=LEVELS, default='Bachelor')

    def __str__(self):
        return self.name

    def get_type(self):
        if self.obligative:
            return "O"
        else:
            return "Z"


class State(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    picture = models.ImageField(null=True, blank=True, default='no-img.png')
    website = models.URLField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True)
    program = models.ForeignKey(Program, on_delete=models.SET_NULL, null=True)
    country = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.CharField(max_length=100, null=True)
    course = models.ManyToManyField(Course, related_name='course', blank=True)
    course_teacher = models.ManyToManyField(Course, related_name='course_teacher', blank=True)
    viti = models.IntegerField(choices=YEARS, default=1)
    semester = models.IntegerField(choices=SEMESTER, default=1)
    level = models.CharField(max_length=100, choices=LEVELS, default=1)


    def get_website(self):
        if self.website[0:4] != 'http':
            return 'http://' + self.website
        else:
            return self.website

    def __str__(self):
        if self.first_name and not self.last_name:
            return self.first_name
        elif self.first_name and self.last_name:
            return self.first_name + ' ' + self.last_name
        else:
            return 'Student'


def create_profile(sender, **kwargs):
    if kwargs['created']:
        student = Student.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class New(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    picture = models.ImageField(null=True, blank=True)
    create_date = models.DateTimeField(default=datetime.now)

    def get_content(self):
        return self.content[:150] + '...'

    def __str__(self):
        return self.title



class Grade(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    grade = models.IntegerField(default=0)

    def __str__(self):
        return self.student.student.first_name + ' ' + self.student.student.last_name


class Upload(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    file = models.FileField(upload_to='files/', validators=[FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])])
    upload_time = models.DateTimeField(default=datetime.now, null=True)

    def get_extension_short(self):
        ext = str(self.file).split(".")
        ext = ext[len(ext)-1]

        if ext == 'doc' or ext == 'docx':
            return 'word'
        elif ext == 'pdf':
            return 'pdf'
        elif ext == 'xls' or ext == 'xlsx':
            return 'excel'
        elif ext == 'ppt' or ext == 'pptx':
            return 'powerpoint'
        elif ext == 'zip' or ext == 'rar' or ext == '7zip':
            return 'archive'

    def __str__(self):
        return str(self.file)[6:]



def get_full_name(self):
    if self.student.first_name and self.student.last_name:
        return self.student.first_name + ' ' + self.student.last_name
    return self.username

User.add_to_class("__str__", get_full_name)


class afatet_provimeve(models.Model):
    emri = models.CharField(max_length=200, null=True, blank=True)
    aktiv = models.BooleanField(default=False)

    def __str__(self):
        if self.emri:
            return self.emri
        return "Afati (" + str(self.pk) + ")"


class Provimet(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(default=datetime.now, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    afati = models.ForeignKey(afatet_provimeve, on_delete=models.CASCADE, null=True)
    refuzuar = models.BooleanField(default=False)

    def __str__(self):
        if self.student.student.first_name and not self.student.student.last_name:
            return self.student.student.first_name + ' - ' + self.afati.emri + ' - ' + self.course.name
        elif self.student.student.first_name and self.student.student.last_name:
            return self.student.student.first_name + ' ' + self.student.student.last_name + ' - ' + self.afati.emri + ' - ' + self.course.name
        else:
            return 'Student' + ' - ' + self.afati.emri

Mentors/sems/forms.py
from django import forms
from .models import Upload, Student, New, Grade, Course, Program, afatet_provimeve
from django.contrib.auth.models import User
from django.forms import CharField


# Upload files to specific course
class UploadFormFile(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ('name', 'file', 'course',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})


# Add/Edit User profile
class UpdateProfile(forms.ModelForm):
    # course = forms.ModelMultipleChoiceField(queryset=Course.objects.all(), widget=forms.CheckboxSelectMultiple)

    is_super = forms.BooleanField(required=False)

    class Meta:
        model = Student
        fields = (
        'first_name', 'last_name', 'email', 'course', 'program', 'country', 'city', 'picture', 'website', 'user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].widget.attrs.update({'hidden': True})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Last Name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Email'})
        self.fields['program'].widget.attrs.update({'class': 'form-control'})
        self.fields['country'].widget.attrs.update({'class': 'form-control'})
        self.fields['city'].widget.attrs.update({'class': 'form-control', 'placeholder': 'City'})
        self.fields['website'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Website'})
        self.fields['course'].widget.attrs.update({'class': 'full-width', 'hidden': True, 'required': False})


# Sign up form
class SignUpForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        try:
            User.objects.get(username__iexact=self.username)
            raise forms.ValidationError('User already exists')
        except User.DoesNotExist:
            return self.username

    def clean_password(self):
        pw1 = self.cleaned_data.get('password1')
        pw2 = self.cleaned_data.get('password2')

        if pw1 and pw2 and pw1 == pw2:
            return pw1
        raise forms.ValidationError("Password doesn't match")


# Select teachers for a specific course
class SelectTeachersForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('first_name', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'] = forms.ModelMultipleChoiceField(queryset=Student.objects.all())
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})


class AddPostForm(forms.ModelForm):
    class Meta:
        model = New
        fields = ('title', 'content', 'picture',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['content'].widget.attrs.update({'class': 'form-control'})
        self.fields['picture'].widget.attrs.update({'class': 'form-control'})


class GradeStudentsForm(forms.ModelForm):
    # student = forms.ChoiceField(choices=[(s.pk, s.first_name + ' ' + s.last_name) for s in Student.objects.all()])

    class Meta:
        model = Grade
        fields = ('student', 'grade',)

    def __init__(self, *args, **kwargs):
        super(GradeStudentsForm, self).__init__(*args, **kwargs)
        # if course:
        # self.fields['student'].widget = forms.ChoiceField(choices=[(s.pk, s.first_name) for s in Student.objects.all()])
        # self.fields['student'].widget = forms.ChoiceField(queryset=Student.objects.values_list('pk', 'first_name'))
        self.fields['student'].widget.attrs.update({'class': 'form-control'})
        self.fields['grade'].widget.attrs.update({'class': 'form-control'})


class DateInput(forms.DateInput):
    input_type = 'date'


class CourseAddForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control'})
        self.fields['program'].widget.attrs.update({'class': 'form-control'})
        self.fields['level'].widget.attrs.update({'class': 'form-control'})
        self.fields['year'].widget.attrs.update({'class': 'form-control'})
        self.fields['semester'].widget.attrs.update({'class': 'form-control'})
        self.fields['start_date'].widget.attrs.update({'class': 'form-control'})
        self.fields['end_date'].widget.attrs.update({'class': 'form-control'})
        self.fields['credits'].widget.attrs.update({'class': 'form-control'})


class ProgramForm(forms.ModelForm):
    class Meta:
        model = Program
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control'})


class AfatetForm(forms.ModelForm):
    class Meta:
        model = afatet_provimeve
        fields = '__all__'
        # widgets = {
        #     'prej': DateInput(),
        #     'deri': DateInput()
        # }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['emri'].widget.attrs.update({'class': 'form-control'})

Mentors/sems/templates/grade_students.html
{% extends 'base_generic.html' %} {% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-xs-12">
            <form method="post">
                <div class="card-box">
                    <h6>{{ course }}</h6> {% csrf_token %} {{ formset.management_form }} {% if formset|length > 0 %} {% for form in formset %}
                    <div class="row justify-content-start border-bottom input-styled">
                        {{ form.id }}
                        <label class="col-md-8 col-6">
                            {{ form.student }}
                        </label>
                        <label class="col-md-4 col-6">
                            {{ form.grade }}
                        </label>
                    </div>
                    {% endfor %} {% else %}
                    <p class="text-danger">No students</p>
                    {% endif %}
                </div>
                <div class="empty-box">
                    <button type="submit" class="btn btn-primary">Save all</button>
                    <a class="btn btn-danger" href="{% url 'course_detail' pk=course.pk %}">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Mentors/sems/templates/post_single.html
{% extends 'base_generic.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-xs-12">
            <div class="card-box">
                {% if post.picture %}
                <div class="single-post-img">
                    {% load static %}
                    <img src="{% static 'uploads/' %}{{ post.picture }}" />
                </div>
                {% endif %}
                <h4>{{ post.title }}</h4>
                <p>{{ post.content|safe }}</p>
            </div>
            {% if user.is_authenticated and user.is_superuser %}
            <div class="empty-box">
                <a class="btn btn-primary" href="{% url 'post_edit' pk=post.pk %}">Edit</a>
                <span class="with-popup">
                    <div class="popup p-delete">
                        <p>Are you sure you want to delete this post?</p>
                        <a href="{% url 'post_delete' pk=post.pk %}">Delete</a>
                    </div>
                    <a class="no-float btn btn-danger">Delete</a>
                </span>
            </div>
            {% endif %}
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="card-box">
                <h5>Latest Posts</h5>
                <ul class="list-unstyled">
                    {% for p in posts %}
                        <li><a href="{% url 'post_single' pk=p.pk %}">{{ p.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card-box">
                <h5>Latest Uploads</h5>
                <ul class="list-unstyled">
                    {% load static %}
                    {% for upload in uploads %}
                        <li><a href="{% static 'uploads/' %}{{ upload.file }}">{{ upload.name }} <small><a href="#">- {{ upload.course }}</a></small></a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Mentors/sems/templates/student_profile.html
{% extends 'base_generic.html' %}


{% block content %}

{% if user.is_superuser or user.student == student %}
<div class="abs-popup">
    <div class="no-shade card-box grades">
        <!-- <h5>Success</h5><br/> -->
        <a onclick="toggleGrades()" class="toggleBtn btn btn-danger"><i class="fas fa-times"></i> Close</a><br><br>
        <table>
            <thead>
                <th>Course</th>
                <th>Grade</th>
            </thead>
            <tbody>
                {% if success %}
                {% for grade in success %}
                <tr>
                    <td>{{ grade.course }}</td>
                    <td>{% if grade.grade >= 5 %}{{ grade.grade }}{% else %}&mdash;{% endif %}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td>Empty dataset</td>
                    <td></td>
                </tr>
                {% endif %}
            </tbody>
        </table><br>
    </div>
</div>
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="no-shade card-box">
                <div class="row">
                    <div class="col-md-3 col-xs-12 text-center">
                        <div class="thumb img-round">
                            <img src="../static/uploads/{% if student.picture %}{{ student.picture }} {% else %}no-img.png {% endif %}" />
                        </div>
                        {% if user.is_authenticated %}
                        {% if user.student.pk == student.pk or user.is_superuser %}
                        <div class="text-left">
                            <br/>
                            <a class="btn btn-primary" style="display: block" href="{% url 'user_edit' pk=student.pk %}"><i class="material-icons">edit</i>Edit</a><br/>
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                    <div class="col-md-9 col-xs-12">
                        <h3>{{ student.first_name }} {{ student.last_name }}</h3>
                        <small class="faded lead">
                            {{ student.get_level_display }} &mdash;
                            <a href="{% url 'program_single' pk=student.program.pk %}" class="text-primary">{{ student.program }}</a>
                        </small>
                        <!-- <br>Semestri: {{ student.semester }}<br> -->
                        <hr/>
                        <!--<br/>-->
                        <div><span class="sm-label label text-primary"><i class="fas fa-map-marker"></i></span> {{ student.city }}, {{ student.country }}</div><br/>
                        <div><span class="sm-label label text-primary"><i class="fas fa-envelope"></i></span> {{ student.email }}</div>
                        {% if student.website %}
                        <br/>
                        <div><span class="sm-label label text-primary"><i class="fas fa-link"></i></span> <a href="{{ student.get_website }}" title="{{ student.get_website }}" target="_blank">{{ student.website }}</a> </div>
                        {% endif %}
                        <hr/>
                        <h5>Enrolled Courses</h5>
                        {% if student.course.all %}
                            {% if student.course.all|length > 8 %}
                            <div class="hide">
                                <div class="white-shadow">
                                    <div onclick="showCourses(this)" id="trigger">Expand <i class="fas fa-angle-down"></i></div>
                                </div>
                            {% endif %}
                                {% for course in student.course.all %}
                                <a class="label" href="{% url 'course_detail' pk=course.pk %}" title="{{ course.summary }}">{{ course }}</a>
                                {% endfor %}
                            {% if student.course.all|length > 8 %}
                            </div>
                            {% endif %}
                            {% else %}
                        <b class="text-danger">No courses</b>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if user.is_superuser or user.student == student %}
            <div class="empty-box text-left">
                <a onclick="toggleGrades()" class="toggleBtn btn btn-primary">Shiko notat</a>
                <a class="float-right btn btn-primary" href="{% url 'provimet' %}">Paraqit provimet</a>
            </div>
            {% endif %}
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="card-box">
                <h6>Overview</h6>
                <table>
                    <tbody>
                        <tr>
                            <td>Average Grade</td>
                            <td>{{ details.grade__avg|floatformat:-2 }}</td>
                        </tr>
                        <tr>
                            <td>Highest Grade</td>
                            <td>{% if not details.grade__max %}&mdash;{% else %}{{ details.grade__max }}{% endif %}</td>
                        </tr>
                        <tr>
                            <td>Lowest Grade</td>
                            <td>{% if not details.grade__min %}&mdash;{% else %}{{ details.grade__min }}{% endif %}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block javascript %}
<script>
    var visible = false;
    var collapsed = true;

    function toggleGrades() {
        if (visible) {
            $('.abs-popup').hide()
        } else {
            $('.abs-popup').show();
            $('.abs-popup').css('display', 'flex');
        }
        visible = !visible;
    }

    function showCourses(btn) {
        var btn = $(btn);

        if (collapsed) {
            btn.html("Collapse <i class=\"fas fa-angle-up\"></i>");
            $(".hide").css("max-height", "unset");
            $(".white-shadow").css({"background": "unset", "z-index": "0"});
        } else {
            btn.html("Expand <i class=\"fas fa-angle-down\"></i>");
            $(".hide").css("max-height", "150");
            $(".white-shadow").css({"background": "linear-gradient(transparent 50%, rgba(255,255,255,.8) 80%)", "z-index": "2"});
        }
        collapsed = !collapsed;
    }
</script>
{% endblock %}

Mentors/sems/templates/upload_file_form.html
{% extends 'base_generic.html' %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-xs-12">
            <form method="post" enctype="multipart/form-data" >
                <div class="card-box">
                    {% csrf_token %}
                    <h6>Upload file</h6>
                    <div class="form-group">
                        File name<br/>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        {{ form.file }}
                    </div>
                    <div class="form-group">
                        <select hidden name="course" required="" id="id_course">
                            <option value="{{ course.pk }}" selected>{{ course }}</option>
                        </select>
                    </div>
                </div>
                <div class="empty-box">
                    <button type="submit" class="btn btn-primary">Upload</button>
                    <a class="btn btn-danger" href="{% url 'course_detail' pk=course.pk %}">Cancel</a>
                </div>
                <hr>
                <small class="faded">Valid files: <b>PDF, Word, Excel, Powepoint, Zip/Rar</b></small>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Mentors/sems/templates/user_profile_edit.html
{% extends 'base_generic.html' %}


{% block javascript %}
{% load static %}
<script src="{% static 'js/ajax.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div class="card-box">
                        <h6>Personal info</h6><br/>
                        {% csrf_token %}
                        {{ form.user }}
                        <div class="form-group">
                            {{ form.first_name }}
                        </div>
                        <div class="form-group">
                            {{ form.last_name }}
                        </div>
                        <div class="form-group">
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="card-box">
                        <h6>Other</h6><br/>
                        <div class="form-group">
                            {{ form.picture }}
                        </div>
                        <div class="form-group">
                            {{ form.website }}
                        </div>                        
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card-box">
                        <h6>Location</h6><br/>
                        <div class="form-group">
                            {{ form.country }}
                        </div>
                        <div class="form-group">
                            {{ form.city }}
                        </div>
                    </div>
                    <div class="card-box">
                        <h6>Course info</h6><br/>
                        <div class="form-group">
                            {{ form.program }}
                        </div>
                        <div class="form-group position-relative">
                            <!-- <div class="block"></div> -->
                            {{ form.course }}<br/>
                            <small class="faded">Hold 'Control', or 'Command' on Mac and select</small>
                        </div>
                    </div>
                    {% if user.is_superuser %}
                    <div class="no-shade card-box">
                        <div class="form-check">
                            {{ form.is_super }} 
                            <label class="form-check-label" for="id_is_super">
                                Superuser
                            </label>
                        </div>
                    </div>
                    {% endif %}
                    <!-- <div class="col-md-6"> -->
                    <div class="empty-box">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a class="btn btn-danger" href="{% url 'student_detail' pk=student.pk%}">Back</a>
                    </div>
                <!-- </div> -->
                </div>
            </div>
        </form>
</div>
{% endblock %}