Courses/urls.py
from django.contrib import admin
from django.urls import path, include
from Courses import views
urlpatterns = [
    path('all/', views.All_courses.as_view(), name='my_courses'),
]

Mentors/Accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'Accounts'

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'login/$', auth_views.LoginView.as_view(template_name='Accounts/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUP.as_view(), name='signup'),

    url(r'login2/$', auth_views.LoginView.as_view(template_name='Accounts/login2.html'), name='login2'),
    url(r'logout2/$', auth_views.LogoutView.as_view(), name='logout2'),
    url(r'signup2/$', views.SignUP.as_view(), name='signup2'),
    url(r'^profile/$', views.view_profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password')

]

Mentors/Mentors/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^Accounts/', include('Accounts.urls', namespace='Accounts')),
    url(r'^Accounts/', include('django.contrib.auth.urls')),
    #url(r'MentorsAccount/', include('MentorsAccount.urls', namespace='Account2')),
    #url(r'MentorsAccount/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^test2/$', views.TestPage2.as_view(), name='test2'),
    url(r'^thanks2/$', views.ThanksPage2.as_view(), name='thanks2'),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r"^groups/", include("groups.urls", namespace="groups"))
]

Mentors/Accounts/models.py
from django.db import models
from django.contrib import auth


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

Mentors/Accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
)


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email address'


class UserCreateForm2(UserCreateForm):

    class Meta2:
        field2 = ('username', 'email', 'password1', 'password2')
        model2 = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.field2['username'].label = 'Display Name'
        self.field2['email'].label = 'Email Address'


class EditProfileForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = (
            'email',
            'first_name',
            'last_name',
        )

Mentors/Accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.http import Http404
from pip._internal.cli.cmdoptions import editable
from requests import request

from . import forms

# Create your views here.


class SignUP(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'Accounts/signup.html'


class SignUp2(CreateView):
    form_class = forms.UserCreateForm2
    success_url = reverse_lazy('login2')
    template_name = 'Accounts/signup2.html'


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'Accounts/profile.html', args)


def edit_profile(requset):

    if requset.method == 'POST':
        form = forms.EditProfileForm(requset.POST, instance=requset.user)

        if form.is_valid():
            form.save()
            return redirect('/Accounts/profile')

    else:
        form = forms.EditProfileForm()
        args = {'form': form}
        return render(requset, 'Accounts/edit_profile.html', args)


def change_password(requset):

    if requset.method == 'POST':
        form = PasswordChangeForm(data=requset.POST, instance=requset.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(requset, form.user)
            return redirect('/Accounts/profile')

        else:
            return redirect('/Accounts/change-password')

    else:
        form = PasswordChangeForm(user=requset.user)
        args = {'form': form}
        return render(requset, 'Accounts/password_change.html', args)

Mentors/Accounts/templates/Accounts/login.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  <div class="container">
      <h1>Login</h1>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-secondary" value="Login">
      </form>

  </div>
{% endblock %}

Mentors/Accounts/templates/Accounts/login2.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  <div class="container">
      <h1>Login as Mentor </h1>

      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-secondary" value="Login">
      </form>

  </div>
{% endblock %}

Mentors/Accounts/templates/Accounts/password_change.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>
{% endblock %}

Mentors/Accounts/templates/Accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
    <a href="{% url 'Accounts:edit_profile' %}" class="btn btn-secondary btn-lg active" role="button">Edit Profile</a>
    <a href="#" class="btn btn-secondary btn-lg active" role="button">Build CV</a>
    <a href="{% url 'Accounts:change_password' %}" class="btn btn-secondary btn-lg active" role="button">Change Password</a>

</div>
{% endblock %}

Mentors/Accounts/templates/Accounts/signup.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  <div class="container">
      <h1>Sign Up</h1>

      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-secondary" value="Sign Up">
      </form>

  </div>
{% endblock %}

Mentors/Accounts/templates/Accounts/signup2.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  <div class="container">
      <h1>Sign Up as Mentor </h1>

      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-secondary" value="Sign Up">
      </form>

  </div>
{% endblock %}